version: '3.1'

services:
  postgres:
    image: postgres:13
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty007
      POSTGRES_DB: lms
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my-network

  user-service:
    build:
      context: ./LMS-system-2.2
      dockerfile: Dockerfile
    container_name: my-app
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qwerty007
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8085:8085"
    networks:
      - my-network

volumes:
  postgres-data:

networks:
  my-network: